ALTER TABLE exhibits
ADD COLUMN IF NOT EXISTS time TEXT,
ADD COLUMN IF NOT EXISTS place TEXT,
ADD COLUMN IF NOT EXISTS introduction TEXT,
ADD COLUMN IF NOT EXISTS image_url TEXT,
ADD COLUMN IF NOT EXISTS thumbnail_url TEXT,
ADD COLUMN IF NOT EXISTS other TEXT;
